name: CI/CD Pipeline # Name of the GitHub Actions workflow

on: # Specifies the events that trigger the workflow
    push: # Trigger on push events to the following branches:
        branches: [main, develop] # The workflow will run when code is pushed to `main` or `develop` branches
    pull_request: # Trigger on pull request events to the following branches
        branches: [main] # The workflow will run when a pull request is opened targeting the 'main' branch

jobs: # Defines the jobs that will run as part of this workflow
    build-test: # Name of the first job
        runs-on: ubuntu-latest # Specifies the type of runner to use (latest version of Ubuntu)

        steps: # List of steps to be executed in this job
            - name: Checkout repository # Step to check out the repository's code
              uses: actions/checkout@v3 # Uses the checkout action to clone the repository

            - name: Setup Node.js # Step to set up Node.js environment
              uses: actions/setup-node@v3 # Uses the setup-node action to install Node.js
              with: # Configuration options for the setup-node action
                node-version: 20 # Specifies the version of Node.js to use
                cache: 'npm' # Caches npm dependencies to speed up the workflow

            - name: Install dependencies # Step to install project dependencies
              run: npm install # Runs the npm install command to install dependencies

            - name: Run tests # Step to run tests
              run: npm test # Runs the `npm test` command to execute the tests

    deploy: # Name of the second job
        needs: build-test # Specifies that this job depends on the `build-test` job
        runs-on: ubuntu-latest # Specifies the type of runner to use (latest version of Ubuntu)

        steps: # List of steps to be executed in this job
            - name: Deploy to Render # Step to deploy the application
              env: # Environment variables fo this step
                RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }} # Uses a secret stored in GitHub
              run: curl -X POST "$RENDER_DEPLOY_HOOK" # Sends a POST request to the Render deploy hook URL to trigger deployment